# Generated by Django 2.2.4 on 2023-11-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0002_auto_20231123_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(default='black', max_length=45),
            preserve_default=False,
        ),
    ]
